CREATE TABLE students(schoolname TEXT, standard TEXT, name TEXT,
                      numbers REAL, code REAL, gender TEXT, dob REAL, age REAL,
                      immu TEXT, disease TEXT, sick TEXT, food TEXT, meals REAL,
                      junk REAL, water REAL, breakfast TEXT, lunch TEXT,
                      snacks TEXT, dinner TEXT, height REAL, magnitude REAL,
                      rate REAL, rates REAL, norma TEXT, abnorma TEXT,
                      tonsil TEXT, allergy TEXT, normal TEXT, abnormal TEXT,
                      paediatric TEXT, answer TEXT, norm TEXT, abn TEXT,
                      nor TEXT, af TEXT, answers TEXT, diet TEXT, nom TEXT,
                      an TEXT, teeth REAL, fill REAL, filled REAL, dent TEXT,
                      den TEXT, ans TEXT, dental TEXT, prob TEXT, probs TEXT,
                      ye TEXT, nots TEXT, eye REAL, eyes REAL, remark TEXT,
                      opthal TEXT, psychological TEXT, psych TEXT, psy TEXT,
                      ps TEXT, nature TEXT, motor TEXT, learning TEXT,
                      learn TEXT)