CREATE TABLE students(schoolname TEXT, standard TEXT, name TEXT,
                      numbers REAL, code REAL, gender TEXT, DOB DATE, age REAL,
                      immu TEXT, disease TEXT, sick TEXT, food TEXT, meals REAL,
                      junk REAL, water REAL, breakfast TEXT, lunch TEXT,
                      snacks TEXT, dinner TEXT, height REAL, magnitude REAL,
                      Rate REAL, Rates REAL, skin TEXT, head TEXT, ear TEXT, 
                      nose TEXT, hearing TEXT, lymph TEXT, CVS TEXT, CNS TEXT,
                      GIT TEXT, general TEXT, tonsil TEXT, allergy TEXT, times TEXT, 
                      breathing TEXT, speech TEXT, bleed TEXT, BT TEXT,
                      paediatric TEXT, carbohydrates TEXT, minerals TEXT, Fats TEXT,
                      Protein TEXT, vitamins TEXT, undernourishhed TEXT, overfed TEXT,
                      obese TEXT, fibre TEXT, nutritional, answers TEXT, diet TEXT, 
                      brush_twice TEXT, mouthwash TEXT, tongue TEXT, toothpaste TEXT, teeth REAL,
                      fill REAL, filled REAL, fluorosis TEXT,gingivitis TEXT,
                      malocclusion TEXT, calculus TEXT, stains TEXT, coated TEXT,
                      gums TEXT, swelling TEXT, sensitivity TEXT, TMJ Text,
                      ans TEXT, dental TEXT, prob TEXT, probs TEXT,
                      ye TEXT, nots TEXT, eye REAL, eyes REAL, remark TEXT,
                      opthal TEXT, psychological TEXT, psych TEXT, psy TEXT,
                      ps TEXT, nature TEXT, intelligence TEXT, NV TEXT,
                      attention TEXT, memory TEXT, motor TEXT)

